### PR TITLE
add apps for each category

### PR DESCRIPTION
**Pull request by Viacheslav1510**

### CODE REVIEW

**Review by Dee68 — APPROVED** [review]
Quite cool but one app (miscellaneous) not included yet.

**Comment by Dee68** [comment]
I think we need to change the navigation bar. I will make some changes and show you a screen short before commit for review.

**Comment by Viacheslav1510** [comment]
No problem, you can change navigation, it's just a standard template

**Comment by Dee68** [comment]
ok

**Comment by Dee68** [comment]
approved

**Pull request merged**
